# Generated by Django 6.0 on 2026-05-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_parcel_is_cod_paid_parcel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
