# Generated by Django 6.0 on 2026-06-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_parcelstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='delivery_address',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='departure_city',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
