# Generated by Django 6.0 on 2026-06-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_driver_parcel_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='city',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_available',
        ),
    ]
