# Generated by Django 6.0 on 2026-06-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_driver_city_driver_is_available'),
    ]

    operations = [
    ]
