# Generated by Django 6.0.6 on 2026-06-04 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_restore_driver_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='cod_credited_to_wallet',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DriverWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='logistics.driver')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('COD_COLLECTION', 'COD Collection'), ('PAYOUT', 'Payout / Cash Drop')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.parcel')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='logistics.driverwallet')),
            ],
        ),
    ]
