# Generated by Django 6.0.6 on 2026-06-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_garage_alter_parcel_status_parcel_current_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badge_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(default='Abrago', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='end_of_day',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('driver', 'Driver'), ('developer', 'Developer')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='start_of_day',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
