# Generated by Django 6.0.6 on 2026-06-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_userprofile_badge_number_userprofile_company_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Garage',
            new_name='Hub',
        ),
        migrations.RenameField(
            model_name='parcel',
            old_name='current_garage',
            new_name='current_hub',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('AT_HUB', 'At Hub'), ('DELIVERED', 'Delivered'), ('REFUSED', 'Refused')], default='CREATED', max_length=20),
        ),
    ]
