"""
Django settings for abrago project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Construisez les chemins à l'intérieur du projet comme ceci : BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Paramètres de développement pour démarrage rapide - inadaptés à la production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# AVERTISSEMENT DE SÉCURITÉ : gardez la clé secrète utilisée en production secrète !
SECRET_KEY = 'django-insecure-*f2@6aaet^c1%=velp7*d(4^by)y*y72)-x44&5#@onrsi4pfh'

# AVERTISSEMENT DE SÉCURITÉ : ne lancez pas l'application avec debug activé en production !
DEBUG = True

# FONCTIONNALITÉ : DÉPLOIEMENT - HÔTES AUTORISÉS
# Permet à l'application Django d'être accessible sur le domaine en direct
# de PythonAnywhere ainsi qu'en local (localhost/127.0.0.1).
ALLOWED_HOSTS = ['Abrare.pythonanywhere.com', 'localhost', '127.0.0.1']


# Définition de l'application

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'logistics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'abrago.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'abrago.wsgi.application'


# Base de données
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Validation du mot de passe
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalisation
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Fichiers statiques (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# FONCTIONNALITÉ : DÉPLOIEMENT - FICHIERS STATIQUES
# Requis pour le déploiement sur PythonAnywhere.
# Indique à la commande 'collectstatic' où regrouper tous les fichiers statiques (CSS, JS, images)
# pour que le serveur web puisse les afficher correctement aux utilisateurs.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configuration de l'e-mail pour Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# TODO: Remplacer par l'adresse e-mail réelle et le mot de passe d'application pour activer l'envoi
EMAIL_HOST_USER = 'abrareyaktine@gmail.com'
EMAIL_HOST_PASSWORD = 'YOUR_APP_PASSWORD_HERE' 

# Configuration de la traduction
LANGUAGES = [
    ('en', 'English'),
    ('fr', 'French'),
]
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]
